---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://trmnl.achtnegen.nl/launchpad/launch/upcoming?limit={{ amount }}
polling_headers: ''
polling_body: ''
id: 189917
custom_fields:
- name: About this plugin
  keyname: author_bio
  field_type: author_bio
  description: Show the one or up to 10 upcoming launches at random order. Show basic information about the flight, what the mission is and when it takes place (UTC Time).<br><br> The information provides is from <a href="thespacedevs.com">thespacedevs.com</a>, an open API. There are limitations for use. Thats why the info is pulled and cached at my end and refreshed every 15 minutes. <br><br> Questions or ideas? Email me or reach out on Discord at @Bas/@Bastronautica.
  email_address: trmnl@achtnegen.nl
- keyname: amount
  field_type: select
  options:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  name: Amount of launches, randomized
  description: Select the amount of you would like to randomize.
  help_text: Select 1 if you always want the latest
name: Launchpad - Upcoming rocket launches
refresh_interval: 1440
